-- CreateEnum
CREATE TYPE "ITAdminRole" AS ENUM ('IT_ADMIN_CENTRAL', 'IT_ADMIN_ACADEMIC', 'IT_ADMIN_ADMISSIONS', 'IT_ADMIN_BURSARY', 'IT_ADMIN_EXAMS', 'IT_ADMIN_STUDENT_AFFAIRS', 'IT_ADMIN_HOSTEL');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "itAdminRole" "ITAdminRole",
ADD COLUMN     "mustChangePassword" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "tempPasswordExpiresAt" TIMESTAMP(3);
